spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/taskdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
